### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by melriksdesign** [ridgekuhn/so-widgets-icon-fap#1] opened 2020-09-14 14:10 UTC
This child-plugin for SO looks like a good one, but it appears to only offer what their font-families function provides.

Is this still in development?  Any notes on what's needed to push it to production?

**Comment by ridgekuhn** [comment] 2020-09-14 20:40
@melriksdesign Hi friend, thanks for your interest! Part of the functionality u mention in the so-widgets-bundle was actually committed by me in order to get it to get it to work with this plugin, lol. Unfortunately, this project got abandoned while I was waiting for the pull request to get approved bc my client no longer needed it. 

iirc, the issues with saving and rendering mentioned in the readme were caused by hardcoding issues which my commit to so-widgets-bundle should have resolved (or opened the door for resolving, anyway). You can find my suggestions to the documentation on how to integrate any custom font with style variations in [that pull request](https://github.com/siteorigin/so-widgets-bundle/pull/989). If nothing else, all the hard work preparing the icon metadata and CSS for Font Awesome Pro is done in this plugin; just drop in your token, run the script, and you'll receive your metadata/CSS files. If you're lucky, this plugin might work as-is?

**Comment by melriksdesign** [comment] 2020-09-18 18:42
50% good news.

What's the final file structure look like?
We don't use yarn or npm.
I can manually add the Font-awesome files if I know where they are supposed to be in relation to the other plug-in files.

Thanks for getting back to me.

**Comment by ridgekuhn** [comment] 2020-09-18 19:51
@melriksdesign I've attached a fresh build using Font Awesome Pro 5.14. I wrote this when 5.12 was current, so hopefully nothing major changed with Font Awesome or siteorigin/so-widgets-bundle. 

You may or may not need the CSS file in /css/all.css depending on how you're implementing Font Awesome, but I recommend taking a look at [Site Origin's](https://github.com/siteorigin/so-widgets-bundle/blob/develop/icons/fontawesome/style.css) icon stylesheet, as the so-widgets-bundle does rely on a couple custom classes to render the icons in the plugin. If you try to use this plugin, it expects the font files to be in /webfonts.

so-widgets-bundle relies on [hardcoded metadata for icons](https://github.com/siteorigin/so-widgets-bundle/blob/develop/icons/fontawesome/filter.php). This plugin compiles it from Font Awesome's YAML file into the data structure so-widgets-bundle expects, stores it as JSON, and [loads it into a PHP array](https://github.com/ridgekuhn/so-widgets-icon-fap/blob/5714208ad22ceed9e478e80b004bc16acc66bcb2/index.php#L79) at runtime to pass to so-widget-bundle's filters. You might want to just convert the metadata to PHP if server load is a concern. 

Good luck, let me know how it goes! I'd be greatly amused if the plugin works as-is!

[so-widgets-icon-fap.zip](https://github.com/ridgekuhn/so-widgets-icon-fap/files/5247808/so-widgets-icon-fap.zip)

**Comment by melriksdesign** [comment] 2020-09-24 02:35
It works!



I don't have a huge budget, but if I can send you some coffee-buying thank you money, please let me know where to send the check.



Cheers!



Rik



---- On Fri, 18 Sep 2020 15:51:24 -0400 ridgekuhn <notifications@github.com> wrote ----




I've attached a fresh build using Font Awesome Pro 5.14. I wrote this when 5.12 was current, so hopefully nothing major changed with Font Awesome or siteorigin/so-widgets-bundle.

You may or may not need the CSS file in /css/all.css depending on how you're implementing Font Awesome, but I recommend taking a look at https://github.com/siteorigin/so-widgets-bundle/blob/develop/icons/fontawesome/style.css icon stylesheet, as the so-widgets-bundle does rely on a couple custom classes to render the icons in the plugin. If you try to use this plugin, it expects the font files to be in /webfonts.

so-widgets-bundle relies on https://github.com/siteorigin/so-widgets-bundle/blob/develop/icons/fontawesome/filter.php. This plugin compiles it from Font Awesome's YAML file into the data structure so-widgets-bundle expects, stores it as JSON, and https://github.com/ridgekuhn/so-widgets-icon-fap/blob/5714208ad22ceed9e478e80b004bc16acc66bcb2/index.php#L79 at runtime to pass to so-widget-bundle's filters. You might want to just convert the metadata to PHP if server load is a concern.

Good luck, let me know how it goes! I'd be greatly amused if the plugin works as-is!

https://github.com/ridgekuhn/so-widgets-icon-fap/files/5247808/so-widgets-icon-fap.zip

**Comment by ridgekuhn** [comment] 2020-09-25 05:33
@melriksdesign Wow, I'm legit shocked!!! I thought it might still be broken! It's very kind of you to offer to support this plugin, but since I'm not supporting it at the moment, I'd feel absolutely terrible accepting money for its development! Best of luck with your project!!!

**Closed as completed by ridgekuhn** 2020-09-25 05:33 UTC
